archArr = [{ Name: 'Gifted',
    Benefits: ['Additional Study',
        'Combat Caster',
        'Fast Caster',
        'Feat: Dominator',
        'Feat: Powerful Caster',
        'Feat: Quick Cast',
        'Feat: Strength of Will',
        'Magic Sensitivity',
        'Rune Reader',
        'Warding Circle']},
    { Name: 'Intellectual',
    Benefits: ['Battlefield Coordination',
        'Feat: Flawless Timing',
        'Feat: Prescient',
        'Feat: Perfect Plot',
        'Feat: Plan of Action',
        'Feat: Quick Thinking',
        'Feat: Unconventional Warfare',
        'Genius',
        'Hyper Perception',
        'Photographic Memory']},
    { Name: 'Mighty',
    Benefits: ['Beat Back',
        'Feat: Back Swing',
        'Feat: Bounding Leap',
        'Feat: Counter Charage',
        'Feat: Invulnerable',
        'Feat: Revitalize',
        'Feat: Shield Breaker',
        'Feat: Vendetta',
        'Feat: Righteous Anger',
        'Tough']},
    { Name: 'Skilled',
    Benefits: ['Ambidexterous',
        'Cagey',
        'Deft',
        'Feat: Defensive Strike',
        'Feat: Disarm',
        'Feat: Swashbuckler',
        'Feat: Untouchable',
        'Preternatural Awareness',
        'Sidestep',
        'Virtuoso']}
];