careerArr = [
    { Name: "Alchemist",
    StartingCareerOnly: false,
    StartingAbilities: ['Grenadier', 'Poison Resistance'],
    StartingConnections: [],
    StartingMilitarySkills: [['Hand Weapon',1], ['Thrown Weapon',1]],
    StartingOccupationalSkills: [['Alchemy',1], ['Medicine',1]],
    StartingSkillChoices: 0,
    StartingSkillChoicesOptions: [],
    StartingSpells: [],
    StartingSpecial: '',
    StartingAssets: ['alchemist\'s leather', 'gas mask', 'traveling alchemist\'s kit', 'any five alchemical grenades', 'grenadier\'s bandolier'],
    StartingAssetChoices: 0,
    StartingAssetChoiceOptions: [],
    StartingGold: 50,
    Abilities: ['Bombmer',
        'Brew Master',
        'Fast Cook',
        'Field Alchemist',
        'Fire in the Hole!',
        'Free Style', 'Grenadier',
        'Poison Resistance'],
    Connections: ['Connections (alchemical order)'],
    MilitarySkills: [['Hand Weapon',2], ['Thrown Weapon',4], ['Unarmed Combat',2]],
    OccupationalSkills: [['Alchemy',4],
        ['Craft (any)',4],
        ['Forgery',2],
        ['General Skills',4],
        ['Medicine',4],
        ['Negotiation',4],
        ['Research',4]
    ]},
    { Name: "Arcane Mechanik",
    StartingCareerOnly: false,
    StartingAbilities: ['Inscribe Formulae'],
    StartingConnections: [],
    StartingMilitarySkills: [],
    StartingOccupationalSkills: [['Craft (gunsmithing)',1],['Craft (metalworking)',1],['Mechanikal Engineering',1]],
    StartingSkillChoices: 1,
    StartingSkillChoicesOptions: [['Hand Weapon',1],['Rifle',1]],
    StartingSpells: ['Arcantrik Bolt', 'Polarity Shield'],
    StartingSpecial: '',
    StartingAssets: ['Rune Etching Kit'],
    StartingAssetChoices: 1,
    StartingAssetChoiceOptions: ['Mechanika Weapon worth up to 750 gc','Mechanika Suit of Armor worth up to 750 gc'],
    StartingGold: 50,
    Abilities: ['\'Jack Marshal',
        'Ace Commander',
        'Arcane Engineer',
        'Drive: Assault',
        'Drive: Pronto',
        'Inscribe Formulae',
        'Resourceful',
        'Steamo'
    ],
    Connections: ['Connections (mechaniks organization)'],
    MilitarySkills: [['Hand Weapon',2], ['Light Artillery',2], ['Rifle',2]],
    OccupationalSkills: [['Command',1]
        ['Craft (any)',4],
        ['Cryptography',3],
        ['General Skills',4],
        ['Mechanikal Engineering',4],
        ['Negotiation',2],
        ['Research',3]
    ]},
    { Name: "Arcanist",
    StartingCareerOnly: false,
    StartingAbilities: ['Great Power'],
    StartingConnections: [],
    StartingMilitarySkills: [],
    StartingOccupationalSkills: [['Lore (Arcane)',1],['Research',1]],
    StartingSkillChoices: 0,
    StartingSkillChoicesOptions: [],
    StartingSpells: ['Arcane Bolt','Aura of Protection','Light in the Darkness'],
    StartingSpecial: 'A character who chooses Arcanist as one of his two starting careers gains the Rune Reader Gifted archetype benefit.',
    StartingAssets: [],
    StartingAssetChoices: 0,
    StartingAssetChoiceOptions: [],
    StartingGold: 75,
    Abilities: ['Arcane Defenses','Arcane Scholar','Great Power','University Education'],
    Connections: ['Connections (magical order)'],
    MilitarySkills: [],
    OccupationalSkills: [['Craft (any)',2],
        ['Etiquette',2],
        ['General Skills',4],
        ['Negotiation',2],
        ['Oratory',2],
        ['Research',4]
    ]},
    { Name: "Aristocrat",
    StartingCareerOnly: true,
    StartingAbilities: ['Good Breeding','Language (any)','Privilege'],
    StartingConnections: ['Connections (nobility)'],
    StartingMilitarySkills: [['Hand Weapon',1]],
    StartingOccupationalSkills: [['Command',1],['Etiquette',1]],
    StartingSkillChoices: 1,
    StartingSkillChoicesOptions: [['Archery',1],['Pistol',1],['Rifle',1]],
    StartingSpells: [],
    StartingSpecial: 'A character who choses Aristocrat as one of his two starting careers gains 50 gc each month from his family holdings.',
    StartingAssets: [''],
    StartingAssetChoices: 0,
    StartingAssetChoiceOptions: [],
    StartingGold: 200,
    Abilities: ['Advisor',
        'Appraise',
        'Battle Plan: Call to Action',
        'Expert Rider',
        'Good Breeding',
        'Language',
        'Natural Leader',
        'Poison Resistance',
        'Privilege',
        'Rallying Cry',
        'Swift Rider'],
    Connections: ['Connections (any)'],
    MilitarySkills: [['Archery',2],
        ['Hand Weapon',3],
        ['Lance',3],
        ['Pistol',2],
        ['Rifle',3]
    ],
    OccupationalSkills: [['Bribery',4],
        ['Command',4],
        ['Cryptography',2],
        ['Deception',4],
        ['Etiquette',4],
        ['General Skills',4],
        ['Law',4],
        ['Negotiation',4],
        ['Oratory',4],
        ['Seduction',4]
    ]},
    { Name: "Bounty Hunter",
    StartingCareerOnly: false,
    StartingAbilities: ['Binding','Take Down'],
    StartingConnections: [],
    StartingMilitarySkills: [],
    StartingOccupationalSkills: [['Detection',1],['Intimidation',1],['Rope Use',1],['Tracking',1]],
    StartingSkillChoices: 2,
    StartingSkillChoicesOptions: [['Crossbow',1],['Hand Weapon',1],['Pistol',1],['Rifle',1],['Unarmed Combat',1]],
    StartingSpells: [],
    StartingSpecial: '',
    StartingAssets: [],
    StartingAssetChoices: 0,
    StartingAssetChoiceOptions: [],
    StartingGold: 75,
    Abilities: ['Binding',
        'Crossbowman',
        'Head-Butt',
        'Language (Five-Cant)',
        'Pursuit',
        'Roll With It',
        'Take Down',
        'Waylay'
    ],
    Connections: ['Connections (any)'],
    MilitarySkills: [['Crossbow',3],
        ['Hand Weapon',2],
        ['Pistol',2],
        ['Rifle',3],
        ['Unarmed Combat',4]
    ],
    OccupationalSkills: [['Bribery',2],
        ['Deception',2],
        ['Disguise',2],
        ['General Skills',4],
        ['Interrogation',2],
        ['Law',2],
        ['Negotiation',4],
        ['Rope Use',4],
        ['Sneak',3],
        ['Streetwise',4],
        ['Tracking',4]
    ]},
    { Name: "Highwayman",
    StartingCareerOnly: false,
    StartingAbilities: ['Ambush','Saddle Shot'],
    StartingMilitarySkills: [['Hand Weapon',1]],
    StartingOccupationalSkills: [['Animal Handling',1],
        ['Detection',1],
        ['Intimidation',1],
        ['Riding',1]
    ],
    StartingSkillChoices: 1,
    StartingSkillChoicesOptions: [['Archery',1],
        ['Crossbow',1],
        ['Pistol',1]
    ],
    StartingSpells: [],
    StartingSpecial: '',
    StartingAssets: ['mask','riding horse','tack'],
    StartingAssetChoices: 0,
    StartingAssetChoiceOptions: [],
    StartingGold: 75,
    Abilities: ['Ambush',
        'Appraise',
        'Binding',
        'Expert Rider',
        'Fast Draw',
        'Fast Reload',
        'Light Cavalry',
        'Prowl',
        'Ride-By Attack',
        'Saddle Shot',
        'Swift Hunter',
        'Swift Rider',
        'Traceless Path',
        'Two-Weapon Fighting',
        'Waylay'
    ],
    Connections: ['Connections (criminal)'],
    MilitarySkills: [['Archery',3],
        ['Crossbow',3],
        ['Hand Weapon',3],
        ['Pistol',3],
        ['Unarmed Combat',3]
    ],
    OccupationalSkills: [['Bribery',2],
        ['Deception',3],
        ['Disguise',2],
        ['General Skills',4],
        ['Interrogation',2],
        ['Negotiation',4],
        ['Rope Use',4],
        ['Seduction',4],
        ['Sneak',4],
        ['Survival',2]
    ]},
    { Name: "Warcaster",
    StartingCareerOnly: true,
    StartingAbilities: ['Bond'],
    StartingMilitarySkills: [['Hand Weapon',1],['Pistol',1]],
    StartingOccupationalSkills: [['Command',1],['Detection',1]],
    StartingSkillChoices: 0,
    StartingSkillChoicesOptions: [],
    StartingSpells: ['Boundless Charge','Convection'],
    StartingAssets: [],
    StartingAssetChoices: 1,
    StartingAssetChoiceOptions: ['warcaster armor (light)',
        'warcaster armor (medium)',
        'mechanika hand weapon',
        'mechanika hand cannon'
    ],
    StartingGold: 0,
    Abilities: ['Bond',
        'Field Marshal: Magical Attack',
        'Field Marshal: Relentless Charge',
        'Field Marshal: Shield Guard',
        'Natural Leader'
    ],
    Connections: ['Connections (kingdom or mercenary company)'],
    MilitarySkills: [['Great Weapon',3],
        ['Hand Weapon',3],
        ['Pistol',3],
        ['Unarmed Combat',2]
    ],
    OccupationalSkills: [['Command',4],
        ['General Skills',4]
    ]}
];