careerArr = [
    {
        Name: "Alchemist",
        StartingCareerOnly: false,
        StartingAbilities: ['Grenadier', 'Poison Resistance'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1], ['Thrown Weapon',1]],
        StartingOccupationalSkills: [['Alchemy',1], ['Medicine',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['alchemist\'s leather', 'gas mask', 'traveling alchemist\'s kit', 'any five alchemical grenades', 'grenadier\'s bandolier'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 50,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Bomber',
            'Brew Master',
            'Fast Cook',
            'Field Alchemist',
            'Fire in the Hole!',
            'Free Style', 'Grenadier',
            'Poison Resistance'
        ],
        Connections: ['Connections (alchemical order)'],
        MilitarySkills: [['Hand Weapon',2], ['Thrown Weapon',4], ['Unarmed Combat',2]],
        OccupationalSkills: [
            ['Alchemy',4],
            ['Craft (any)',4],
            ['Forgery',2],
            ['General Skills',4],
            ['Medicine',4],
            ['Negotiation',4],
            ['Research',4]
        ]
    },
    {
        Name: "Arcane Mechanik",
        StartingCareerOnly: false,
        StartingAbilities: ['Inscribe Formulae'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Craft (gunsmithing)',1],['Craft (metalworking)',1],['Mechanikal Engineering',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Hand Weapon',1],['Rifle',1]],
        StartingSpells: ['Arcantrik Bolt', 'Polarity Shield'],
        StartingSpecial: '',
        StartingAssets: ['Rune Etching Kit'],
        StartingAssetChoices: 1,
        StartingAssetChoiceOptions: ['Mechanika Weapon worth up to 750 gc','Mechanika Suit of Armor worth up to 750 gc'],
        StartingGold: 50,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            '\'Jack Marshal',
            'Ace Commander',
            'Arcane Engineer',
            'Drive: Assault',
            'Drive: Pronto',
            'Inscribe Formulae',
            'Resourceful',
            'Steamo'
        ],
        Connections: ['Connections (mechaniks organization)'],
        MilitarySkills: [['Hand Weapon',2], ['Light Artillery',2], ['Rifle',2]],
        OccupationalSkills: [
            ['Command',1]
            ['Craft (any)',4],
            ['Cryptography',3],
            ['General Skills',4],
            ['Mechanikal Engineering',4],
            ['Negotiation',2],
            ['Research',3]
        ]
    },
    {
        Name: "Arcanist",
        StartingCareerOnly: false,
        StartingAbilities: ['Great Power'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Lore (Arcane)',1],['Research',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: ['Arcane Bolt','Aura of Protection','Light in the Darkness'],
        StartingSpecial: 'A character who chooses Arcanist as one of his two starting careers gains the Rune Reader Gifted archetype benefit.',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: ['Rune Reader'],
        Abilities: ['Arcane Defenses','Arcane Scholar','Great Power','University Education'],
        Connections: ['Connections (magical order)'],
        MilitarySkills: [],
        OccupationalSkills: [
            ['Craft (any)',2],
            ['Etiquette',2],
            ['General Skills',4],
            ['Negotiation',2],
            ['Oratory',2],
            ['Research',4]
        ]
    },
    {
        Name: "Aristocrat",
        StartingCareerOnly: true,
        StartingAbilities: ['Good Breeding','Language (any)','Privilege'],
        StartingConnections: ['Connections (nobility)'],
        StartingMilitarySkills: [['Hand Weapon',1]],
        StartingOccupationalSkills: [['Command',1],['Etiquette',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Pistol',1],['Rifle',1]],
        StartingSpells: [],
        StartingSpecial: 'A character who choses Aristocrat as one of his two starting careers gains 50 gc each month from his family holdings.',
        StartingAssets: [''],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 200,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Advisor',
            'Appraise',
            'Battle Plan: Call to Action',
            'Expert Rider',
            'Good Breeding',
            'Language',
            'Natural Leader',
            'Poison Resistance',
            'Privilege',
            'Rallying Cry',
            'Swift Rider'
        ],
        Connections: ['Connections (any)'],
        MilitarySkills: [
            ['Archery',2],
            ['Hand Weapon',3],
            ['Lance',3],
            ['Pistol',2],
            ['Rifle',3]
        ],
        OccupationalSkills: [
            ['Bribery',4],
            ['Command',4],
            ['Cryptography',2],
            ['Deception',4],
            ['Etiquette',4],
            ['General Skills',4],
            ['Law',4],
            ['Negotiation',4],
            ['Oratory',4],
            ['Seduction',4]
        ]
    },
    {
        Name: "Bounty Hunter",
        StartingCareerOnly: false,
        StartingAbilities: ['Binding','Take Down'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Intimidation',1],['Rope Use',1],['Tracking',1]],
        StartingSkillChoices: 2,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Crossbow',1],['Hand Weapon',1],['Pistol',1],['Rifle',1],['Unarmed Combat',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Binding',
            'Crossbowman',
            'Head-Butt',
            'Language (Five-Cant)',
            'Pursuit',
            'Roll With It',
            'Take Down',
            'Waylay'
        ],
        Connections: ['Connections (any)'],
        MilitarySkills: [
            ['Crossbow',3],
            ['Hand Weapon',2],
            ['Pistol',2],
            ['Rifle',3],
            ['Unarmed Combat',4]
        ],
        OccupationalSkills: [
            ['Bribery',2],
            ['Deception',2],
            ['Disguise',2],
            ['General Skills',4],
            ['Interrogation',2],
            ['Law',2],
            ['Negotiation',4],
            ['Rope Use',4],
            ['Sneak',3],
            ['Streetwise',4],
            ['Tracking',4]
        ]
    },
    {
        Name: "Cutthroat",
        StartingCareerOnly: false,
        StartingAbilities: ['Anatomical Precision','Backstab','Prowl'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1]],
        StartingOccupationalSkills: [['Intimidation',1],['Sneak',1],['Streetwise',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Crossbow',1],['Thrown Weapon',1],['Unarmed Combat',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Anatomical Precision',
            'Backstab',
            'Blood Spiller',
            'Camouflage',
            'Chain Attack: Bleed Out',
            'Fast Draw',
            'Language (Five Cant)',
            'Prowl',
            'Specialization (Assassin Blade)',
            'Two-Weapon Fighting',
            'Waylay'
        ],
        Connections: ['Connections (criminal)'],
        MilitarySkills: [
            ['Crossbow',2],
            ['Hand Weapon',4],
            ['Thrown Weapon',3],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['General Skills',4],
            ['Interrogation',2],
            ['Sneak',4],
            ['Streetwise',4]
        ]
    },
    {
        Name: "Duelist",
        StartingCareerOnly: false,
        StartingAbilities: ['Parry','Riposte'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1],['Pistol',1]],
        StartingOccupationalSkills: [['Gambling',1],['Intimidation',1],['Jumping',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Acrobatics',
            'Fast Draw',
            'Gunfighter',
            'Parry',
            'Precision Strike',
            'Quick Work',
            'Riposte',
            'Roll With It',
            'Two-Weapon Fighting'
        ],
        Connections: [],
        MilitarySkills: [
            ['Hand Weapon',4],
            ['Pistol',4],
            ['Thrown Weapon',3],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['Etiquette',2],
            ['General Skills',4],
            ['Law',2],
            ['Oratory',2],
            ['Seduction',3],
            ['Streetwise',2]
        ]
    },
    {
        Name: "Explorer",
        StartingCareerOnly: false,
        StartingAbilities: ['Big Game Hunter','Language (any)','Port of Call'],
        StartingConnections: ['Connections (patron)'],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Medicine',1],['Navigation',1],['Survival',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Hand Weapon',1],['Pistol',1],['Rifle',1]],
        StartingSpells: [],
        StartingSpecial: 'A character who chooses Explorer as one of his two starting careers gains 25 gc each month from his patron for as long as he continues to explore new regions, report back regularly, and bring his patron occasional gifts from exotic places.',
        StartingAssets: ['map case','spyglass'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 150,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Battle Plan: Reconnaissance',
            'Big Game Hunter',
            'Disease Resistance',
            'Expert Rider',
            'Language',
            'Natural Leader',
            'Poison Resistance',
            'Port of Call',
            'Signal Language',
            'Swift Rider'
        ],
        Connections: ['Connections (wealthy patrons)','Connections (isolated tribe or people)'],
        MilitarySkills: [
            ['Archery',2],
            ['Crossbow',2],
            ['Hand Weapon',2],
            ['Pistol',2],
            ['Rifle',3],
            ['Thrown Weapon',2],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['Command',4],
            ['Craft (any)',2],
            ['Cryptography',2],
            ['Etiquette',2],
            ['General Skills',4],
            ['Medicine',2],
            ['Navigation',4],
            ['Negotiation',4],
            ['Rope Use',4],
            ['Survival',4]
        ]
    },
    {
        Name: "Fell Caller",
        StartingCareerOnly: false,
        StartingAbilities: ['Fell Call: Signal Call','Fell Call: Sonic Blast'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Command',1],['Fell Calling',2],['Lore (Trollkin)',1],['Oratory',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Great Weapon',1],['Hand Weapon',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Battle Plan: Call to Action',
            'Fell Call: Cacophony',
            'Fell Call: Call of Defiance',
            'Fell Call: Ground Shaker',
            'Fell Call: Heroic Ballad',
            'Fell Call: Reverberation',
            'Fell Call: Signal Call',
            'Fell Call: Sonic Blast',
            'Legacy of Bragg',
            'Natural Leader'
        ],
        Connections: ['Connections (Kriel)'],
        MilitarySkills: [
            ['Great Weapon',3],
            ['Hand Weapon',3],
            ['Thrown Weapon',3],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Command',4],
            ['Fell Calling',4],
            ['General Skills',4],
            ['Oratory',4],
            ['Seduction',2]
        ]
    },
    {
        Name: "Field Mechanik",
        StartingCareerOnly: false,
        StartingAbilities: ['\'Jack Marshal','Bodge','Hit the Deck!'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Command',1],['Craft (metalworking)',1],['Mechanikal Engineering',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Hand Weapon',1],['Pistol',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['mechanik\'s toolkit','light laborjack with up to 200gc of weapons'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 25,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            '\'Jack Masrhal',
            'Ace Commander',
            'Bodge',
            'Dodger',
            'Drive: Ancillary Attack',
            'Drive: Assault',
            'Drive: Off Road',
            'Drive: Pronto',
            'Hit the Deck!',
            'Iron Sentinel',
            'Scrounge',
            'Steamo',
            'Tune Up'
        ],
        Connections: ['Connections (mechaniks organization)'],
        MilitarySkills: [['Hand Weapon',2],['Pistol',2]],
        OccupationalSkills: [
            ['Command',3],
            ['Craft (any)',4],
            ['General Skills',4],
            ['Mechanikal Engineering',4],
            ['Negotiation',3]
        ]
    },
    {
        Name: "Gun Mage",
        StartingCareerOnly: false,
        StartingAbilities: ['Craft Rune Shot','Fast Reload'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Intimidation',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Pistol',1],['Rifle',1]],
        StartingSpells: ['Rune Shot: Accuracy','Rune Shot: Brutal','Rune Shot: Thunderbolt'],
        StartingSpecial: '',
        StartingAssets: ['ammo bandolier','rune shot casting kit','powder','10 rounds of ammunition'],
        StartingAssetChoices: 1,
        StartingAssetChoiceOptions: ['magelock pistol','magelock rifle'],
        StartingGold: 25,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Arcane Precision',
            'Craft Rune Shot',
            'Fast Draw',
            'Fast Reload',
            'Gunfighter',
            'Keen Eyed'
        ],
        Connections: ['Connections (gun mage order)'],
        MilitarySkills: [['Pistol',4],['Rifle',4]],
        OccupationalSkills: [
            ['General Skills',4],
            ['Seduction',2]
        ]
    },
    {
        Name: "Highwayman",
        StartingCareerOnly: false,
        StartingAbilities: ['Ambush','Saddle Shot'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1]],
        StartingOccupationalSkills: [
            ['Animal Handling',1],
            ['Detection',1],
            ['Intimidation',1],
            ['Riding',1]
        ],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Crossbow',1],['Pistol',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['mask','riding horse','tack'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Ambush',
            'Appraise',
            'Binding',
            'Expert Rider',
            'Fast Draw',
            'Fast Reload',
            'Light Cavalry',
            'Prowl',
            'Ride-By Attack',
            'Saddle Shot',
            'Swift Hunter',
            'Swift Rider',
            'Traceless Path',
            'Two-Weapon Fighting',
            'Waylay'
        ],
        Connections: ['Connections (criminal)'],
        MilitarySkills: [
            ['Archery',3],
            ['Crossbow',3],
            ['Hand Weapon',3],
            ['Pistol',3],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Bribery',2],
            ['Deception',3],
            ['Disguise',2],
            ['General Skills',4],
            ['Interrogation',2],
            ['Negotiation',4],
            ['Rope Use',4],
            ['Seduction',4],
            ['Sneak',4],
            ['Survival',2]
        ]
    },
    {
        Name: "Investigator",
        StartingCareerOnly: false,
        StartingAbilities: ['Astute','Language (any)'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [
            ['Detection',1],
            ['Forensic Science',1],
            ['Interrogation',1],
            ['Law',1],
            ['Medicine',1],
            ['Sneak',1]
        ],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military', 
        StartingSkillChoicesOptions: [['Hand Weapon',1],['Pistol',1]],
        StartingSpells: [],
        StartingSpecial: 'A character who chooses Investigator as one of his two starting careers gains the Hyper Perception Intellectual archetype benefit.',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 100,
        ResSecondCareers: [],
        FreeBenefits: ['Hyper Perception'],
        Abilities: [
            'Anatomical Precision',
            'Astute',
            'Iron Will',
            'Language',
            'Prowl',
            'Sign Language',
            'Truth Reader'
        ],
        Connections: ['Connections (any)'],
        MilitarySkills: [['Hand Weapon',2],['Pistol',2],['Unarmed Combat',2]],
        OccupationalSkills: [
            ['Cryptography',4],
            ['Deception',4],
            ['Etiquette',2],
            ['Forensic Science',4],
            ['General Skills',4],
            ['Interrogation',4],
            ['Law',4],
            ['Medicine',2],
            ['Negotiation',3],
            ['Research',4],
            ['Sneak',4],
            ['Streetwise',4]
        ]
    },
    {
        Name: "Iron Fang",
        StartingCareerOnly: true,
        StartingAbilities: ['Fast Rearm (Blasting Pike)','Specialization (Blasting Pike)'],
        StartingConnections: ['Connections (Khadoran military)'],
        StartingMilitarySkills: [['Great Weapon',1],['Sheild',1]],
        StartingOccupationalSkills: [['Command',1],['Survival',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: 'A character starting with the Iron Fang career must choose between Aristocrat, Military Officer, Soldier, or Warcaster for his second career.',
        StartingAssets: ['blasting pike','spear head','10 blasting heads','Iron Fang full plate','shield'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 25,
        ResSecondCareers: ['Aristocrat','Military Officer','Soldier','Warcaster'],
        FreeBenefits: [],
        Abilities: [
            'Defensive Line',
            'Fast Arm (Blasting Pike)',
            'Hyper Awareness',
            'Load Bearing',
            'Precision Strike',
            'Relentless Charge',
            'Rock Solid',
            'Specialization (Blasting Pike)',
            'Swift Rider'
        ],
        Connections: ['Connections (Khadoran military)'],
        MilitarySkills: [['Great Weapon',4],['Lance',4],['Shield',4],['Unarmed Combat',3]],
        OccupationalSkills: [['Command',4],['General Skills',4],['Survival',2]]
    },
    {
        Name: "Knight",
        StartingCareerOnly: false,
        StartingAbilities: ['Cleave','Defender'],
        StartingConnections: ['Connections (knightly order)'],
        StartingMilitarySkills: [['Great Weapon',1],['Hand Weapon',1],['Sheild',1]],
        StartingOccupationalSkills: [['Command',1],['Etiquette',1],['Lore (knightly order)',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '', 
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 100,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Cavalry Charge',
            'Cleave',
            'Combat Rider',
            'Defender',
            'Defensive Line',
            'Expert Rider',
            'Iron Will',
            'Load Bearing',
            'Natural Leader',
            'Precision Strike',
            'Press the Attack',
            'Relentless Charge',
            'Ride-By Attack',
            'Shield Slam'
        ],
        Connections: ['Connections (knightly order)'],
        MilitarySkills: [['Great Weapon',4],['Hand Weapon',4],['Lance',4],['Shield',4],['Unarmed Combat',3]],
        OccupationalSkills: [['Command',4],['Etiquette',2],['General Skills',4],['Law',2]]
    },
    {
        Name: "Mage Hunter",
        StartingCareerOnly: false,
        StartingAbilities: ['Arcane Assassin','Iron Will'],
        StartingConnections: ['Connections (Retribution of Scyrah)'],
        StartingMilitarySkills: [['Hand Weapon',1]],
        StartingOccupationalSkills: [['Climbing',1],['Jumping',1],['Sneak',1],['Tracking',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Crossbow',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Arcane Assassin',
            'Camouflage',
            'Crackshot',
            'Crossbowman',
            'Fast Draw',
            'Fast Reload',
            'Iron Will',
            'Mage Killer',
            'Parry',
            'Quick Work',
            'Shadow Magic',
            'Traceless Path'
        ],
        Connections: ['Connections (Retribution of Scyrah)'],
        MilitarySkills: [['Archery',4],['Crossbow',4],['Hand Weapon',4],['Thrown Weapon',2]],
        OccupationalSkills: [
            ['Deception',2],
            ['Disguise',2],
            ['General Skills',4],
            ['Rope Use',3],
            ['Sneak',4],
            ['Survival',2],
            ['Tracking',4]
        ]
    },
    {
        Name: "Man-at-Arms",
        StartingCareerOnly: false,
        StartingAbilities: ['Defensive Line','Shield Guard'],
        StartingConnections: [],
        StartingMilitarySkills: [['Great Weapon',1],['Shield',1]],
        StartingOccupationalSkills: [['Command',1],['Detection',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Hand Weapon',1],['Pistol',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 100,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Bodyguard',
            'Cleave',
            'Defensive Line',
            'Girded',
            'Iron Will',
            'Load Bearing',
            'Retaliatory Strike',
            'Set Defense',
            'Shield Guard',
            'Shield Slam',
            'Specialization (Halberd)',
            'Specialization (Spear)'
        ],
        Connections: ['Connections (employer)'],
        MilitarySkills: [
            ['Great Weapon',4],
            ['Hand Weapon',3],
            ['Pistol',3],
            ['Shield',4],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Command',3],
            ['Craft (metalworking)',2],
            ['General Skills',4]
        ]
    },
    {
        Name: "Military Officer",
        StartingCareerOnly: false,
        StartingAbilities: ['Battle Plan: Call to Action','Natural Leader','Team Leader'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1]],
        StartingOccupationalSkills: [['Command',1],['Medicine',1],['Navigation',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Great Weapon',1],['Pistol',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['officer\'s uniform'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 100,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            '\'Jack Marshal',
            'Ace Commander',
            'Battle Commander',
            'Battle Plan: Call to Action',
            'Battle Plan: Coordinated Strike',
            'Battle Plan: Desperate Pace',
            'Battle Plan: Go to Ground',
            'Cavalry Charge',
            'Defender',
            'Drive: Assault',
            'Drive: Pronto',
            'Expert Rider',
            'Good Breeding',
            'Natural Leader',
            'Port of Call',
            'Ride-By Attack',
            'Saddle Shot',
            'Signal Language',
            'Team Leader'
        ],
        Connections: ['Connections (mercenary company or kingdom\'s military)'],
        MilitarySkills: [
            ['Great Weapon',4],
            ['Hand Weapon',4],
            ['Pistol',4]
        ],
        OccupationalSkills: [
            ['Command',4],
            ['Cryptography',4],
            ['Etiquette',4],
            ['General Skills',4],
            ['Interrogation',4],
            ['Law',4],
            ['Medicine',4],
            ['Navigation',4],
            ['Oratory',4]
        ]
    },
    {
        Name: "Pirate",
        StartingCareerOnly: false,
        StartingAbilities: ['Gang','Steady','Specialization (Cutlass)'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1]],
        StartingOccupationalSkills: [['Climbing',1],['Intimidation',1],['Sailing',1],['Swimming',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Pistol',1],['Thrown Weapon',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Binding',
            'Disease Resistance',
            'Gang',
            'Gunfighter',
            'Head-Butt',
            'Languages',
            'Port of Call',
            'Quick Work',
            'Specialization (Cutlass)',
            'Steady',
            'Sucker!',
            'Waylay'
        ],
        Connections: ['Connections (pirate crew)'],
        MilitarySkills: [
            ['Hand Weapon',3],
            ['Light Artillery',2],
            ['Pistol',3],
            ['Rifle',2],
            ['Thrown Weapon',3],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Command',2],
            ['Deception',3],
            ['General Skills',4],
            ['Navigation',4],
            ['Negotiation',2],
            ['Rope Use',4],
            ['Sailing',4]
        ]
    },
    {
        Name: "Pistoleer",
        StartingCareerOnly: false,
        StartingAbilities: ['Fast Draw','Gunfighter','Return Fire'],
        StartingConnections: [],
        StartingMilitarySkills: [['Pistol',1]],
        StartingOccupationalSkills: [['Detection',1],['Intimidation',1],['Sneak',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['ammo bandolier','ammunition for 10 shots'],
        StartingAssetChoices: 1,
        StartingAssetChoiceOptions: ['hand cannon','pair of repeating pistols'],
        StartingGold: 50,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Chain Attack: Pin Down',
            'Dodger',
            'Fast Draw',
            'Fast Reload',
            'Gunfighter',
            'Return Fire',
            'Swift Hunter',
            'Targeteer',
            'Two-Weapon Fighting'
        ],
        Connections: [],
        MilitarySkills: [['Pistol',4]],
        OccupationalSkills: [
            ['Craft (gunsmithing)',2],
            ['General Skills',4],
            ['Sneak',3]
        ]
    },
    {
        Name: "Priest of Menoth",
        StartingCareerOnly: false,
        StartingAbilities: ['Dispel'],
        StartingConnections: ['Connections (Menite temple)'],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Lore (Menite faith)',1],['Oratory',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Great Weapon',1],['Hand Weapon',1]],
        StartingSpells: ['Guided Blade','Ignite','Immolation'],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Choir',
            'Language',
            'Natural Leader',
            'Rallying Cry',
            'University Education'
        ],
        Connections: ['Connections (character\'s church)'],
        MilitarySkills: [['Great Weapon',3],['Hand Weapon',3],['Shield',2]],
        OccupationalSkills: [
            ['Command',2],
            ['Cryptography',2],
            ['Etiquette',4],
            ['General Skills',4],
            ['Law',4],
            ['Medicine',4],
            ['Negotiation',4],
            ['Oratory',4],
            ['Research',4]
        ]
    },
    {
        Name: "Priest of Morrow",
        StartingCareerOnly: false,
        StartingAbilities: ['Empower'],
        StartingConnections: ['Connections (Morrowan church)'],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Lore (Morrowan faith)',1],['Medicine',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Great Weapon',1],['Hand Weapon',1]],
        StartingSpells: ['Blade of Radiance','Solovin\'s Boon','True Sight'],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Choir',
            'Language',
            'Natural Leader',
            'Rallying Cry',
            'University Education'
        ],
        Connections: ['Connections (character\'s church)'],
        MilitarySkills: [['Great Weapon',3],['Hand Weapon',3],['Shield',2]],
        OccupationalSkills: [
            ['Command',2],
            ['Cryptography',2],
            ['Etiquette',4],
            ['General Skills',4],
            ['Law',4],
            ['Medicine',4],
            ['Negotiation',4],
            ['Oratory',4],
            ['Research',4]
        ]
    },
    {
        Name: "Ranger",
        StartingCareerOnly: false,
        StartingAbilities: ['Camouflage','Pathfinder'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1]],
        StartingOccupationalSkills: [['Detection',1],['Sneak',1],['Survival',1],['Tracking',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Crossbow',1],['Pistol,1'],['Rifle',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Battle Plan: Go to Ground',
            'Battle Plan: Reconnaissance',
            'Battle Plan: Shadow Camouflage',
            'Disease Resistance',
            'Fast Reload',
            'Light Cavalry',
            'Night Fighter',
            'Pathfinder',
            'Prowl',
            'Saddle Shot',
            'Signal Language',
            'Swift Hunter',
            'Swift Rider',
            'Traceless Path'
        ],
        Connections: [],
        MilitarySkills: [
            ['Archery',4],
            ['Crossbow',3],
            ['Hand Weapon',2],
            ['Pistol',2],
            ['Rifle',4],
            ['Thrown Weapon',4],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Command',3],
            ['Craft (any)',2],
            ['Cryptography',1],
            ['General Skills',4],
            ['Medicine',3],
            ['Navigation',4],
            ['Rope Use',4],
            ['Sneak',4],
            ['Survival',4],
            ['Tracking',4]
        ]
    },
    {
        Name: "Rifleman",
        StartingCareerOnly: false,
        StartingAbilities: ['Crackshot','Dual Shot','Marksman'],
        StartingConnections: [],
        StartingMilitarySkills: [['Rifle',1]],
        StartingOccupationalSkills: [['Climbing',1],['Detection',1],['Survival',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['ammo bandolier','powder','ammunition for 10 shots'],
        StartingAssetChoices: 1,
        StartingAssetChoiceOptions: ['heavy rifle','repeating long rifle'],
        StartingGold: 50,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Crackshot',
            'Dual Shot',
            'Fast Reload',
            'Marksman',
            'Night Fighter',
            'Return Fire',
            'Saddle Shot',
            'Sniper',
            'Swift Hunter',
            'Targeteer'
        ],
        Connections: [],
        MilitarySkills: [['Rifle',4]],
        OccupationalSkills: [['Craft (gunsmithing)',4],['General Skills',4],['Survival',3]]
    },
    {
        Name: "Soldier",
        StartingCareerOnly: false,
        StartingAbilities: ['Find Cover','Sentry'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Driving',1],['Medicine',1],['Survival',1]],
        StartingSkillChoices: 2,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [
            ['Hand Weapon',1],
            ['Pistol',1],
            ['Crossbow',1],
            ['Great Weapon',1],
            ['Rifle',1],
            ['Thrown Weapon',1]
        ],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 100,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            '\'Jack Marshal',
            'Cautious Advance',
            'Cavalry Charge',
            'Disease Resistance',
            'Fast Reload',
            'Find Cover',
            'Grenadier',
            'Hit the Deck!',
            'Language',
            'Ride-By Attack',
            'Roll With It',
            'Saddle Shot',
            'Sentry'
        ],
        Connections: ['Connections (kingdom military or mercenary company)'],
        MilitarySkills: [
            ['Crossbow',3],
            ['Great Weapon',4],
            ['Light Artillery',3],
            ['Hand Weapon',3],
            ['Pistol',3],
            ['Rifle',4],
            ['Shield',2],
            ['Thrown Weapon',3],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Command',3],
            ['General Skills',4],
            ['Medicine',3],
            ['Navigation',2],
            ['Sneak',2],
            ['Survival',3]
        ]
    },
    {
        Name: "Sorcerer (Fire)",
        StartingCareerOnly: true,
        StartingAbilities: ['Immunity: Fire'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Survival',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Crossbow',1],['Hand Weapon',1]],
        StartingSpells: ['Fire Starter','Howling Flames','Wall of Fire'],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Camouflage',
            'Dodger',
            'Elemental Mastery',
            'Immunity: Fire',
            'Traceless Path'
        ],
        Connections: [],
        MilitarySkills: [
            ['Archery',3],
            ['Crossbow',3],
            ['Hand Weapon',3],
            ['Thrown Weapon',2],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['General Skills',4],
            ['Sneak',3],
            ['Survival',3]
        ]
    },
    {
        Name: "Sorcerer (Ice)",
        StartingCareerOnly: true,
        StartingAbilities: ['Immunity: Cold'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Survival',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Crossbow',1],['Hand Weapon',1]],
        StartingSpells: ['Blizzard','Chiller','Ice Bolt'],
        StartingSpecial: '',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Camouflage',
            'Dodger',
            'Elemental Mastery',
            'Immunity: Cold',
            'Traceless Path'
        ],
        Connections: [],
        MilitarySkills: [
            ['Archery',3],
            ['Crossbow',3],
            ['Hand Weapon',3],
            ['Thrown Weapon',2],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['General Skills',4],
            ['Sneak',3],
            ['Survival',3]
        ]
    },
    {
        Name: "Sorcerer (Stone)",
        StartingCareerOnly: true,
        StartingAbilities: [],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Survival',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Crossbow',1],['Hand Weapon',1]],
        StartingSpells: ['Battering Ram','Solid Ground','Stone Stance'],
        StartingSpecial: 'Stone sorcerers begin with +1 PHY and +1 to their racial maximum PHY at each level.',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Camouflage',
            'Dodger',
            'Elemental Mastery',
            'Traceless Path'
        ],
        Connections: [],
        MilitarySkills: [
            ['Archery',3],
            ['Crossbow',3],
            ['Hand Weapon',3],
            ['Thrown Weapon',2],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['General Skills',4],
            ['Sneak',3],
            ['Survival',3]
        ]
    },
    {
        Name: "Sorcerer (Storm)",
        StartingCareerOnly: true,
        StartingAbilities: [],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Detection',1],['Survival',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Archery',1],['Crossbow',1],['Hand Weapon',1]],
        StartingSpells: ['Razor Wind','Storm Tossed','Wind Blast'],
        StartingSpecial: 'Storm sorcerers begin with +1 SPD and +1 to their racial maximum SPD at each level.',
        StartingAssets: [],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Camouflage',
            'Dodger',
            'Elemental Mastery',
            'Traceless Path'
        ],
        Connections: [],
        MilitarySkills: [
            ['Archery',3],
            ['Crossbow',3],
            ['Hand Weapon',3],
            ['Thrown Weapon',2],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['General Skills',4],
            ['Sneak',3],
            ['Survival',3]
        ]
    },
    {
        Name: "Spy",
        StartingCareerOnly: false,
        StartingAbilities: ['Battle Plan: Shadow','Cover Identity','Language (choose one)'],
        StartingConnections: ['Connections (intelligence network)'],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [['Command',1],['Deception',1],['Detection',1],['Disguise',1],['Sneak',1]],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Hand Weapon',1],['Pistol',1],['Thrown Weapon',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['forged identity papers'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 100,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Battle Plan: Shadow',
            'Cover Identity',
            'Iron Will',
            'Language',
            'Poison Resistance',
            'Prowl',
            'Signal Language',
            'Truth Reader',
            'Waylay'
        ],
        Connections: ['Connections (any)'],
        MilitarySkills: [
            ['Hand Weapon',3],
            ['Pistol',3],
            ['Thrown Weapon',3],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Bribery',4],
            ['Command',3],
            ['Cryptography',4],
            ['Deception',4],
            ['Disguise',4],
            ['Escape Artist',4],
            ['Etiquette',4],
            ['Forgery',4],
            ['General Skills',4],
            ['Interrogation',4],
            ['Law',4],
            ['Lock Picking',2],
            ['Negotiation',4],
            ['Seduction',4],
            ['Sneak',4],
            ['Streetwise',4]
        ]
    },
    {
        Name: "Stormblade",
        StartingCareerOnly: true,
        StartingAbilities: ['Blaster','Specialization (Storm Glaive)'],
        StartingConnections: ['Connections (Cygnaran military)'],
        StartingMilitarySkills: [['Great Weapon',1]],
        StartingOccupationalSkills: [['Command',1],['Detection',1],['Etiquette',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: 'A character starting with the Stormblade career must choose between Aristocrat, Knight, Man-at-Arms, Military Officer, Soldier, or Warcaster for his second career.',
        StartingAssets: ['Storm Glaive','Storm Knight Armor'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 0,
        ResSecondCareers: ['Aristocrat','Knight','Man-at-Arms','Military Officer','Soldier','Warcaster'],
        FreeBenefits: [],
        Abilities: [
            '\'Jack Marshal',
            'Blaster',
            'Gunfighter',
            'Load Bearing',
            'Quick Work',
            'Relentless Charge',
            'Specialization (Storm Glaive)'
        ],
        Connections: ['Connections (Cygnaran military)'],
        MilitarySkills: [['Great Weapon',4]],
        OccupationalSkills: [
            ['Command',4],
            ['Etiquette',2],
            ['General Skills',4],
            ['Medicine',2]
        ]
    },
    {
        Name: "Thief",
        StartingCareerOnly: false,
        StartingAbilities: ['Conniver','Dodger'],
        StartingConnections: [],
        StartingMilitarySkills: [],
        StartingOccupationalSkills: [
            ['Bribery',1],
            ['Deception',1],
            ['Escape Artist',1],
            ['Lock Picking',2],
            ['Pickpocket',2],
            ['Sneak',1],
            ['Streetwise',1]
        ],
        StartingSkillChoices: 1,
        StartingSkillChoicesType: 'Military',
        StartingSkillChoicesOptions: [['Hand Weapon',1],['Thrown Weapon',1]],
        StartingSpells: [],
        StartingSpecial: '',
        StartingAssets: ['thief\'s tools'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 75,
        ResSecondCareers: [],
        FreeBenefits: [],
        Abilities: [
            'Appraise',
            'Camouflage',
            'Card Sharp',
            'Conniver',
            'Dodger',
            'Fleet Foot',
            'Get Away',
            'Language (Five Cant)',
            'Parry',
            'Prowl',
            'Traceless Path'
        ],
        Connections: ['Connections (criminal)'],
        MilitarySkills: [
            ['Hand Weapon',3],
            ['Pistol',2],
            ['Thrown Weapon',3],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['Bribery',4],
            ['Craft (any)',2],
            ['Deception',4],
            ['Disguise',4],
            ['Escape Artist',4],
            ['Etiquette',1],
            ['Forgery',4],
            ['General Skills',4],
            ['Law',2],
            ['Lock Picking',4],
            ['Negotiation',4],
            ['Pickpocket',4],
            ['Sneak',4],
            ['Streetwise',4]
        ]
    },
    {
        Name: "Trencher",
        StartingCareerOnly: true,
        StartingAbilities: ['Bayonet Charge','Dig In'],
        StartingConnections: ['Connections (Cygnaran military)'],
        StartingMilitarySkills: [['Great Weapon',1],['Rifle',1],['Thrown Weapon',1]],
        StartingOccupationalSkills: [['Command',1],['Detection',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: [],
        StartingSpecial: 'A character starting with the Trencher career must choose between Military Officer, Ranger, Rifleman, Soldier, or Warcaster for his second career.',
        StartingAssets: ['ammo bandolier','bayonet','entrenching spade','military rifle','3 smoke grenades','Trencher medium infantry armor'],
        StartingAssetChoices: 0,
        StartingAssetChoiceOptions: [],
        StartingGold: 25,
        ResSecondCareers: ['Military Officer','Ranger','Rifleman','Soldier','Warcaster'],
        FreeBenefits: [],
        Abilities: [
            '\'Jack Marshal',
            'Anatomical Precision',
            'Bayonet Charge',
            'Bomber',
            'Dig In',
            'Fire in the Hole!',
            'Grenadier',
            'Hit the Deck!',
            'Relentless Charge',
            'Specialization (Bayonet)'
        ],
        Connections: ['Connections (Cygnaran military)'],
        MilitarySkills: [
            ['Great Weapon',3],
            ['Light Artillery',4],
            ['Hand Weapon',3],
            ['Pistol',3],
            ['Rifle',4],
            ['Thrown Weapon',4],
            ['Unarmed Combat',3]
        ],
        OccupationalSkills: [
            ['Command',3],
            ['General Skills',4],
            ['Interrogation',3],
            ['Medicine',3],
            ['Sneak',3],
            ['Survival',3]
        ]
    },
    {
        Name: "Warcaster",
        StartingCareerOnly: true,
        StartingAbilities: ['Bond'],
        StartingConnections: [],
        StartingMilitarySkills: [['Hand Weapon',1],['Pistol',1]],
        StartingOccupationalSkills: [['Command',1],['Detection',1]],
        StartingSkillChoices: 0,
        StartingSkillChoicesType: '',
        StartingSkillChoicesOptions: [],
        StartingSpells: ['Boundless Charge','Convection'],
        StartingSpecial: 'Change the character\'s arcane tradition to focuser if he has another arcane career. A warcaster can boost only with mechanikal weapons they are bonded to.',
        StartingAssets: [],
        StartingAssetChoices: 1,
        StartingAssetChoiceOptions: [
            'warcaster armor (light)',
            'warcaster armor (medium)',
            'mechanika hand weapon',
            'mechanika hand cannon'
        ],
        ResSecondCareers: [],
        FreeBenefits: [],
        StartingGold: 0,
        Abilities: [
            'Bond',
            'Field Marshal: Magical Attack',
            'Field Marshal: Relentless Charge',
            'Field Marshal: Shield Guard',
            'Natural Leader'
        ],
        Connections: ['Connections (kingdom or mercenary company)'],
        MilitarySkills: [
            ['Great Weapon',3],
            ['Hand Weapon',3],
            ['Pistol',3],
            ['Unarmed Combat',2]
        ],
        OccupationalSkills: [
            ['Command',4],
            ['General Skills',4]
        ]
    }
];
