optKNGArr =
[
    {
        Name: 'Arcane Tempest Gun Mage',
        Career1: 'Gun Mage',
        ReqRaces: ['Human'],
        ResCareers: ['Gun Mage'],
        ResSecondCareers: ['Aristocrat','Horseman','Military Officer','Pistoleer','Ranger','Rifleman','Soldier','Spy','Warcaster'],
        StartingAssets: ['Armored great coat'],
        StartingConnections: [{ Name: 'Cygnaran military', Type: 'Specific' }],
        AdditionalAbilities: [{ Name: 'Runesmith' }],
        AdditionalSpells: ['Rune Shot: Disruption']
    },
    {
        Name: 'Cygnaran Warcaster',
        Career1: 'Warcaster',
        ReqRaces: ['Human'],
        ResCareers: ['Warcaster'],
        ResSecondCareers:
        [
            'Arcane Mechanik',
            'Arcanist',
            'Aristocrat',
            'Field Mechanik',
            'Gun Mage',
            'Horseman',
            'Knight',
            'Man-at-Arms',
            'Military Officer',
            'Pistoleer',
            'Ranger',
            'Rifleman',
            'Soldier',
            'Sorcerer (Fire)',
            'Sorcerer (Ice)',
            'Sorcerer (Stone)',
            'Sorcerer (Storm)',
            'Stormblade',
            'Trencher'
        ],
        StartingConnections: [{ Name: 'Cygnaran military', Type: 'Specific' }],
        StartingSpells: ['Arcane Bolt','Blur'],
        SpellList:
        [
            'Arcane Blast',
            'Arcane Bolt',
            'Arcane Strike',
            'Aura of Protection',
            'Blur',
            'Chain Lightning',
            'Deceleration',
            'Deadeye',
            'Disruptor',
            'Earthquake',
            'Electrical Blast',
            'Electrify',
            'Fail Safe',
            'Force Field',
            'Force Hammer',
            'Fortify',
            'Foxhole',
            'Guided Fire',
            'Heightened Reflexes',
            'Jump Start',
            'Lightning Shroud',
            'Positive Charge',
            'Refuge',
            'Return Fire',
            'Snipe',
            'Tide of Steel',
            'Voltaic Lock'
        ]
    },
    {
        Name: 'Illuminated Arcanist',
        Career1: 'Arcanist',
        ReqRaces: ['Human'],
        ResCareers: ['Arcanist'],
        StartingConnections: [{ Name: 'Order of Illumination', Type: 'Specific' }],
        StartingSpells: ['Eyes of Truth','Guided Blade','Occultation'],
        SpellList:
        [
            'Arcane Strike',
            'Banishing Ward',
            'Blade of Radiance',
            'Blessings of War',
            'Daylight',
            'Eyes of Truth',
            'Exorcism',
            'Force Hammer',
            'Force of Faith',
            'Guided Blade',
            'Hex Blast',
            'Lamentation',
            'Light in the Darkness',
            'Occultation',
            'Purification',
            'Shield of Faith',
            'Star Fire',
            'Sunburst',
            'True Sight'
        ]
    },
    {
        Name: 'Stormguard',
        Career1: 'Man-at-Arms',
        Career2: 'Stormblade',
        AdditionalStartingAbilities: [{ Name: 'Set Defense' }, { Name: 'Specialization', Type: 'Specific', Property: 'Voltaic Halberd' }],
        RemovedStartingAbilities: [{ Name: 'Blaster' }, { Name: 'Deffensive Line' }, { Name: 'Specialization', Type: 'Specific', Property: 'Storm Glaive' }],
        AdditionalStartingAssets: ['voltaic halberd'],
        RemovedStartingAssets: ['storm glaive']
    },
    {
        Name: 'Storm Lance',
        Career1: 'Knight',
        Career2: 'Stormblade',
        AdditionalStartingOccupationalSkills: [{ Name: 'Riding', Level: 1 }],
        AdditionalStartingAbilities: [{ Name: 'Cavalry Charge' }],
        RemovedStartingAbilities: [{ Name: 'Cleave' }, { Name: 'Defender' }],
        AdditionalStartingAssets: ['electro lance','shield','warhorse with tack and Storm Knight barding'],
        RemovedStartingAssets: ['storm glaive']
    },
    {
        Name: 'Trencher Commando',
        Career1: 'Ranger',
        Career2: 'Trencher',
        AdditionalStartingAbilities: [{ Name: 'Anatomical Precision' }, { Name: 'Prowl' }],
        RemvoedStartingAbilities: [{ Name: 'Bayonet Charge' }, { Name: 'Dig In' }],
        AdditionalStartingAssets: ['carbine','trench knife','3 explosive grenades'],
        RemovedStartingAbilities: ['bayonet','entrenching spade','military rifle']
    },
    {
        Name: 'Greylord',
        Career1: 'Arcanist',
        ReqRaces: ['Human'],
        ResCareers: ['Arcanist'],
        ResSecondCareers:
        [
            'Alchemist',
            'Arcane Mechanik',
            'Aristocrat',
            'Explorer',
            'Horseman',
            'Investigator',
            'Military Officer',
            'Sorcerer (Fire)',
            'Sorcerer (Ice)',
            'Sorcerer (Stone)',
            'Sorcerer (Storm)',
            'Spy',
            'Warcaster'
        ],
        StartingConnections: [{ Name: 'Greylords Covenant', Type: 'Specific' }],
        StartingSpells: ['Blizzard','Frostbite','Protection from Cold'],
        SpellList:
        [
            'Banishing Ward',
            'Battle Rage',
            'Blizzard',
            'Chiller',
            'Deep Freeze',
            'Fog of War',
            'Freezing Grip',
            'Frostbite',
            'Gallows',
            'Guided Blade',
            'Hand of Fate',
            'Hoarfrost',
            'Icy Bolt',
            'Icy Grip',
            'Influence',
            'Inhospitable Ground',
            'Iron Flesh',
            'Light in the Darkness',
            'Overmind',
            'Power Booster',
            'Protection from Cold',
            'Rift',
            'Shatter Storm',
            'Storm Tossed',
            'Tempest',
            'True Sight',
            'Wind Blast',
            'Winter Storm',
            'Zephyr'
        ]
    },
    {
        Name: 'Khadoran Warcaster',
        Career1: 'Warcaster',
        ReqRaces: ['Human'],
        ResCareers: ['Warcaster'],
        ResSecondCareers:
        [
            'Arcane Mechanik',
            'Arcanist',
            'Aristocrat',
            'Assault Kommando',
            'Greylord',
            'Horseman',
            'Investigator',
            'Iron Fang',
            'Military Officer',
            'Pistoleer',
            'Ranger',
            'Rifleman',
            'Soldier',
            'Sorcerer (Fire)',
            'Sorcerer (Ice)',
            'Sorcerer (Stone)',
            'Sorcerer (Storm)',
            'Spy'
        ],
        StartingConnections: [{ Name: 'Khadoran military', Type: 'Specific' }],
        StartingSpells: ['Boundless Charge','Jump Start','Razor Wind'],
        SpellList:
        [
            'Battering Ram',
            'Battle Rage',
            'Boundless Charge',
            'Eliminator',
            'Fog of War',
            'Freezing Grip',
            'Gallows',
            'Grind',
            'Guided Blade',
            'Infernal Machine',
            'Inhospitable Ground',
            'Iron Flesh',
            'Jump Start',
            'Locomotion',
            'Ravager',
            'Razor Wind',
            'Redline',
            'Rift',
            'Shatter Storm',
            'Superiority',
            'Temper Metal',
            'Tempest',
            'Tide of Steel',
            'Transference',
            'Watcher',
            'Wind Blast'
        ]
    },
    {
        Name: 'Iron Fang Uhlan',
        Career1: 'Horseman',
        Career2: 'Iron Fang',
        AdditionalStartingAbilities: [{ Name: 'Fast Rearm', Type: 'Specific', Property: 'Blasting Lance' }],
        RemovedStartingAbilities: [{ Name: 'Fast Rearm', Type: 'Specific', Property: 'Blasting Pike' }],
        AdditionalStartingAssets: ['blasting lance','10 blasting heads','Pozdyov warhorse'],
        RemovedStartingAssets: ['blasting pike','warhorse with tack and heavy barding']
    }
];
