langCoreArr = [
    'Aeric',
    'Caspian',
    'Cygnaran',
    'Five Cant',
    'Gobberish',
    'Idrian',
    'Khadoran',
    'Khurzic',
    'Kossite',
    'Llaelese',
    'Molgur',
    'Molgur-Og',
    'Molgur-Trul',
    'Morridane',
    'Ordic',
    'Rhulic',
    'Scharde',
    'Shyr',
    'Thurian',
    'Umbrean'
];
