milSkillsArr = [
        { Name: "Archery", BaseStat: "POI" },
	{ Name: "Crossbow", BaseStat: "POI" },
	{ Name: "Great Weapon", BaseStat: "PRW" },
	{ Name: "Hand Weapon", BaseStat: "PRW" },
        { Name: "Lance", BaseStat: "PRW" },
        { Name: "Light Artillery", BaseStat: "POI" },
	{ Name: "Pistol", BaseStat: "POI" },
	{ Name: "Rifle", BaseStat: "POI" },
        { Name: "Shield", BaseStat: "PRW" },
	{ Name: "Thrown Weapon", BaseStat: "PRW" },
	{ Name: "Unarmed Combat", BaseStat: "PRW" }
];

occSkillsArr = [
	{ Name: "Alchemy", BaseStat: "INT" },
	{ Name: "Bribery", BaseStat: "Social" },
	{ Name: "Command", BaseStat: "Social" },
	{ Name: "Craft", BaseStat: "INT" },
	{ Name: "Cryptography", BaseStat: "INT" },
	{ Name: "Deception", BaseStat: "Social" },
	{ Name: "Disguise", BaseStat: "INT" },
	{ Name: "Escape Artist", BaseStat: "AGL" },
	{ Name: "Etiquette", BaseStat: "Social" },
	{ Name: "Fell Calling", BaseStat: "POI" },
	{ Name: "Forensic Science", BaseStat: "INT" },
	{ Name: "Forgery", BaseStat: "AGL" },
	{ Name: "Forgery", BaseStat: "INT" },
	{ Name: "Interrogation", BaseStat: "Social" },
	{ Name: "Law", BaseStat: "INT" },
	{ Name: "Lock Picking", BaseStat: "AGL" },
	{ Name: "Mechanikal Engineering", BaseStat: "INT" },
	{ Name: "Medicine", BaseStat: "INT" },
	{ Name: "Navigation", BaseStat: "PER" },
	{ Name: "Negotiation", BaseStat: "Social" },
	{ Name: "Oratory", BaseStat: "Social" },
	{ Name: "Pickpocket", BaseStat: "AGL" },
	{ Name: "Research", BaseStat: "INT" },
	{ Name: "Rope Use", BaseStat: "AGL" },
	{ Name: "Sailing", BaseStat: "INT" },
	{ Name: "Sailing", BaseStat: "STR" },
	{ Name: "Seduction", BaseStat: "Social" },
	{ Name: "Sneak", BaseStat: "AGL" },
	{ Name: "Streetwise", BaseStat: "PER" },
	{ Name: "Survival", BaseStat: "PER" },
	{ Name: "Tracking", BaseStat: "PER" },
	{ Name: "Animal Handling", BaseStat: "Social" },
	{ Name: "Climbing", BaseStat: "AGL" },
	{ Name: "Detection", BaseStat: "PER" },
	{ Name: "Driving", BaseStat: "AGL" },
	{ Name: "Gambling", BaseStat: "PER" },
	{ Name: "Intimidation", BaseStat: "Social" },
	{ Name: "Jumping", BaseStat: "PHY" },
	{ Name: "Lore", BaseStat: "INT" },
	{ Name: "Riding", BaseStat: "AGL" },
	{ Name: "Swimming", BaseStat: "STR" }
];
