spellsCoreArr =
[
    {
        Name: 'Arcane Bolt',
        Cost: 2,
        Range: 12,
        AOE: '-',
        POW: 11,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 236
    },
    {
        Name: 'Arcane Strike',
        Cost: 1,
        Range: 8,
        AOE: '-',
        POW: 8,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 236
    },
    {
        Name: 'Arcantrik Bolt',
        Cost: 2,
        Range: 10,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 236
    },
    {
        Name: 'Ashen Cloud',
        Cost: 2,
        Range: 'CTRL',
        AOE: 3,
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 236
    },
    {
        Name: 'Ashes to Ashes',
        Cost: 4,
        Range: 8,
        AOE: '*',
        POW: 10,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 236
    },
    {
        Name: 'Aura of Protection',
        Cost: 2,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 236
    },
    {
        Name: 'Awareness',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 236
    },
    {
        Name: 'Banishing Ward',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Barrier of Flames',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Battering Ram',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Batten Down the Hatches',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Black Out',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Blade of Radiance',
        Cost: 2,
        Range: 10,
        AOE: '-',
        POW: 10,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Blazing Effigy',
        Cost: 4,
        Range: 'SELF',
        AOE: '*',
        POW: 14,
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Blessing of Health',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Blessing of Morrow',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Blessings of War',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Blizzard',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Brittle Frost',
        Cost: 3,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Boundless Charge',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Broadside',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Celerity',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Chain Lightning',
        Cost: 3,
        Range: 10,
        AOE: '-',
        POW: 10,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Chiller',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Cleansing Fire',
        Cost: 3,
        Range: 8,
        AOE: 3,
        POW: 14,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Convection',
        Cost: 2,
        Range: 10,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 237
    },
    {
        Name: 'Crevasse',
        Cost: 3,
        Range: 8,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Crusader\'s Call',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Daylight',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Deceleration',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Deep Freeze',
        Cost: 3,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Earthquake',
        Cost: 3,
        Range: 10,
        AOE: 5,
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Earth\'s Cradle',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Earthsplitter',
        Cost: 4,
        Range: 10,
        AOE: 3,
        POW: 14,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Electrical Blast',
        Cost: 3,
        Range: 8,
        AOE: 3,
        POW: 13,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Electrify',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Eliminator',
        Cost: 3,
        Range: 8,
        AOE: 3,
        POW: 13,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Entangle',
        Cost: 1,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Eyes of Truth',
        Cost: 2,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Extinguisher',
        Cost: 2,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Fail Safe',
        Cost: 3,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Fair Winds',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Fire Group',
        Cost: 2,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Fire Starter',
        Cost: 1,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: '*',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Flames of Wrath',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Flare',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Fog of War',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 238
    },
    {
        Name: 'Force Field',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Force Hammer',
        Cost: 4,
        Range: 10,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Force of Faith',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Fortify',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Foxhole',
        Cost: 2,
        Range: 'CTRL',
        AOE: 5,
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Freezing Grip',
        Cost: 4,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Freezing Mist',
        Cost: 4,
        Range: 'SELF',
        AOE: '*',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Frozen Ground',
        Cost: 3,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Frostbite',
        Cost: 2,
        Range: 'SP8',
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 239
    },
    {
        Name: 'Fuel the Flames',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Full Throttle',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Grind',
        Cost: 3,
        Range: 10,
        AOE: '-',
        POW: 14,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Guided Blade',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Guided Fire',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Hand of Fate',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Heal',
        Cost: 4,
        Range: '*',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Heightened Reflexes',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Hex Blast',
        Cost: 3,
        Range: 10,
        AOE: 3,
        POW: 13,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Hoarfrost',
        Cost: 3,
        Range: 8,
        AOE: 3,
        POW: 14,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Howling Flames',
        Cost: 2,
        Range: 'SP8',
        AOE: '-',
        POW: 10,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Hymn of Battle',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 240
    },
    {
        Name: 'Hymn of Passage',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Hymn of Shielding',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Ice Bolt',
        Cost: 2,
        Range: 10,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Ice Shield',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Icy Grip',
        Cost: 2,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Ignite',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Immolation',
        Cost: 2,
        Range: 8,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Inferno',
        Cost: 3,
        Range: 10,
        AOE: 3,
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Influence',
        Cost: 1,
        Range: 10,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Inhospitable Ground',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Iron Aggression',
        Cost: 3,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Jackhammer',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Jump Start',
        Cost: 1,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Lamentation',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Light in the Darkness',
        Cost: 1,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Lightning Tendrils',
        Cost: 3,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Locomotion',
        Cost: '1+',
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Mirage',
        Cost: 3,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Obliteration',
        Cost: 4,
        Range: 10,
        AOE: 4,
        POW: 15,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Occultation',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Overmind',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 241
    },
    {
        Name: 'Polarity Shield',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Positive Charge',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Power Booster',
        Cost: 1,
        Range: 5,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Prayer For Guidance',
        Cost: 3,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Protection from Cold',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Protection from Corrosion',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Protection From Electricity',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Protection From Fire',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Purification',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Raging Winds',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Razor Wind',
        Cost: 2,
        Range: 10,
        AOE: '-',
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Redline',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Refuge',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Return Fire',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rift',
        Cost: 3,
        Range: 8,
        AOE: 4,
        POW: 13,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Righteous Flames',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rime',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rock Hammer',
        Cost: 3,
        Range: 10,
        AOE: 3,
        POW: 14,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rock Wall',
        Cost: 2,
        Range: 'CTRL',
        AOE: 'WALL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rune Shot: Accuracy',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rune Shot: Black Penny',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rune Shot: Brutal',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 242
    },
    {
        Name: 'Rune Shot: Detonator',
        Cost: 3,
        Range: 'SELF',
        AOE: '*',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Earth Shaker',
        Cost: 3,
        Range: 'SELF',
        AOE: '*',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Fire Beacon',
        Cost: 2,
        Range: 'SELF',
        AOE: '*',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Freeze Fire',
        Cost: 4,
        Range: 'SELF',
        AOE: '-',
        POW: '-', 
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Heart Stopper',
        Cost: 4,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Iron Shot',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Molten Shot',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Momentum',
        Cost: 4,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Phantom Seeker',
        Cost: 3,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Shadow Fire',
        Cost: 2,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 243
    },
    {
        Name: 'Rune Shot: Silencer',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Rune Shot: Spell Cracker',
        Cost: 3,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Rune Shot: Spontaneous Combustion',
        Cost: 1,
        Range: 'SELF',
        AOE: '*',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Rune Shot: Thunderbolt',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Rune Shot: Trick Shot',
        Cost: 2,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Sanguine Blessing',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Sea of Fire',
        Cost: 4,
        Range: 'SELF',
        AOE: '*',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Shatter Storm',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Shield of Faith',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Shock Wave',
        Cost: 4,
        Range: 'SELF',
        AOE: '*',
        POW: 13,
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Short Out',
        Cost: 1,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Snipe',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Solid Ground',
        Cost: 2,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Solovin\'s Boon',
        Cost: 1,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Star Fire',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Staying Winter\'s Hand',
        Cost: 2,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Stone Stance',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Stone Strength',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Storm Tossed',
        Cost: 1,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Sunburst',
        Cost: 3,
        Range: 10,
        AOE: 3,
        POW: 13,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Superiority',
        Cost: 3,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 244
    },
    {
        Name: 'Telekinesis',
        Cost: 2,
        Range: 8,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: '*',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Temper Metal',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Tempest',
        Cost: 4,
        Range: 8,
        AOE: 4,
        POW: 12,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Tide of Steel',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Tornado',
        Cost: 4,
        Range: 10,
        AOE: '-',
        POW: 13,
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Transference',
        Cost: 2,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Triage',
        Cost: 2,
        Range: 'B2B',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'True Path',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'True Sight',
        Cost: 2,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Vision',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Voltaic Lock',
        Cost: 4,
        Range: 10,
        AOE: '*',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Wall of Fire',
        Cost: 2,
        Range: 'CTRL',
        AOE: 'WALL',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'White Out',
        Cost: 4,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Wind Blast',
        Cost: 2,
        Range: 'CTRL',
        AOE: 5,
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Wind Strike',
        Cost: 1,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Wings of Air',
        Cost: 2,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Winter Storm',
        Cost: 3,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    },
    {
        Name: 'Zephyr',
        Cost: 3,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Core Rules',
        Page: 245
    }
];

spellsKNGArr =
[
    {
        Name: 'Arcane Blast',
        Cost: 3,
        Range: 10,
        AOE: '3',
        POW: '13',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Kings, Nations, and Gods',
        Page: 91
    },
    {
        Name: 'Blur',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Kings, Nations, and Gods',
        Page: 91
    },
    {
        Name: 'Deadeye',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Kings, Nations, and Gods',
        Page: 91
    },
    {
        Name: 'Disruptor',
        Cost: 2,
        Range: 10,
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'YES',
        Book: 'Kings, Nations, and Gods',
        Page: 91
    },
    {
        Name: 'Exorcism',
        Cost: 2,
        Range: 'SELF',
        AOE: 'CTRL',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Kings, Nations, and Gods',
        Page: 91
    },
    {
        Name: 'Lightning Shroud',
        Cost: 2,
        Range: 6,
        AOE: '-',
        POW: '-',
        UP: 'YES',
        OFF: 'NO',
        Book: 'Kings, Nations, and Gods',
        Page: 91
    },
    {
        Name: 'Rune Shot: Disruption',
        Cost: 2,
        Range: 'SELF',
        AOE: '-',
        POW: '-',
        UP: 'NO',
        OFF: 'NO',
        Book: 'Kings, Nations, and Gods',
        Page: 91
    }
];
